TopAccount/Controllers/TopController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VBIDE = Microsoft.Vbe.Interop;
using Excel = Microsoft.Office.Interop.Excel;
using ClosedXML.Excel;
using TopAccount.Models;

namespace TopAccount.Controllers
{
    public class TopController : Controller
    {
        public SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString);
        public ActionResult Index()
        {
            Consolidated _model = Bind();
            ViewBag.Display = "none";
            return View(_model);
        }

        private Consolidated Bind()
        {
            Parameter model = new Parameter();
            DataTable dt = new DataTable();//GetSL();
            dt.Columns.Add("Role");

            string[] _SL = new string[] {"EAS","SAP","ORC","ECAS","EAIS" };

            for(int i = 0; i < _SL.Length; i++)
            {
                DataRow dr = dt.NewRow();
                dr["Role"] = _SL[i].ToString();
                    
                dt.Rows.Add(dr);
            }

            model.SLId = "EAS";


            //if (dt.Rows.Count == 1) { model.SLId = dt.Rows[0]["Role"].ToString(); }
            //else { model.SLId = "EAS"; }

            for (int i = 0; i < dt.Rows.Count; i++)
            {
                string Role = dt.Rows[i]["Role"].ToString();
                model.SL.Add(new SelectListItem { Text = Role, Value = Role });
            }

              

            Consolidated _model = new Consolidated();
            _model.item2 = model;
            return _model;
        }

        [HttpPost]
        public ActionResult Index(Consolidated model, string cookieValue)
        {
            ViewBag.Display = "block";
            string SL = model.item2.SLId;
                     
           
                
                ControllerContext.HttpContext.Response.Cookies.Add(new HttpCookie("dlc", cookieValue));
                return getFinal(SL);
            

            //return GreaterTo(SL, Finyear, from, to, From, To);

        }

        private ActionResult getFinal(string SL)
        {



            DataSet ds = GetData(SL);
            DataTable dt_Account_Wise_Revenue = ds.Tables[0];
            DataTable dt_Org_100 = ds.Tables[1];

            DataTable dt = GetData_Top15(SL);

            string templatePath = string.Empty;

            templatePath = Server.MapPath("~/Template/"+SL+"_TopAccounts_OrgClassification.xlsx");

            var wb = new XLWorkbook(templatePath);
            IXLWorksheet Worksheet = wb.Worksheet("AccountWise_Revenue&TopAccounts");
            Worksheet.Row(19).Cell(1).InsertData(dt_Account_Wise_Revenue.Rows);

            IXLWorksheet Worksheet1 = wb.Worksheet("Org 300 Accounts_Charts");
            Worksheet1.Row(3).Cell(2).InsertData(dt_Org_100.Rows);

            IXLWorksheet Worksheet2 = wb.Worksheet("Top 15 Accounts");
            Worksheet2.Row(3).Cell(1).InsertData(dt.Rows);

            string filename = "";

            //string month_diff=""
            //if(From==To)
            //{
            //    string k = From =="04" ? "Apr"
            //     month_diff = From;
            //}


            string snapshot = DateTime.Now.ToString("ddMMMyyyy_HHmm");
            filename = SL + "_" + GETUser() + "_TopAccounts_OrgClassification_" + snapshot + ".xlsx";
            wb.SaveAs(Server.MapPath("~/ExcelOperation/" + filename));

            //GenerateReport(filename);

            string fullPath = Path.Combine(Server.MapPath("~/ExcelOperation"), filename);
            return File(fullPath, "application/vnd.ms-excel", filename);
        }

        private static string GETUser()
        {
            string user = "";

            string[] machineUser = System.Web.HttpContext.Current.User.Identity.Name.Split('\\');
            if (machineUser.Length == 2)
                user = machineUser[1];
            return user;
        }

        private DataSet GetData(string SL)
        {

            string SP = "";
            if (SL == "EAS") { SP = "sp_SL_Data_OrgClassification_EAS_Online"; } else { SP = "sp_SL_Data_OrgClassification_Online"; }
            SqlCommand cmd = new SqlCommand(SP, con);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandTimeout = int.MaxValue;
            //cmd.Parameters.AddWithValue("@UserId", GETUser());
            if (SL != "EAS") { cmd.Parameters.AddWithValue("@SL", SL); }
              
            SqlDataAdapter sdr = new SqlDataAdapter(cmd);
            DataSet ds = new DataSet();
            sdr.Fill(ds);
            return ds;
        }

        private DataTable GetData_Top15(string SL)
        {

            string SP = "";
            SP = "SP_Dinesh_DP_Top15Accounts"; 
            SqlCommand cmd = new SqlCommand(SP, con);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandTimeout = int.MaxValue;
            cmd.Parameters.AddWithValue("@ParamSL", SL);
            SqlDataAdapter sdr = new SqlDataAdapter(cmd);
            DataSet ds = new DataSet();
            sdr.Fill(ds);
            return ds.Tables[0];
        }

        private DataTable GetSL()
        {
            SqlCommand cmd = new SqlCommand("spBEGetSU_dummy", con);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandTimeout = int.MaxValue;
            cmd.Parameters.AddWithValue("@userid", GETUser());

            SqlDataAdapter sdr = new SqlDataAdapter(cmd);
            DataSet ds = new DataSet();
            sdr.Fill(ds);
            return ds.Tables[0];
        }

      



        void GenerateReport(string fname)
        {


            Microsoft.Office.Interop.Excel.Application oExcel;
            Microsoft.Office.Interop.Excel.Workbook oBook = default(Microsoft.Office.Interop.Excel.Workbook);
            VBIDE.VBComponent oModule;
            //try
            {

                string folder = "~/ExcelOperation";
                var myDir = new DirectoryInfo(Server.MapPath(folder));

                string templatefolder = "~/template";
                var templatemyDir = new DirectoryInfo(Server.MapPath(templatefolder));

                String sCode;
                Object oMissing = System.Reflection.Missing.Value;
                //instance of excel
                oExcel = new Microsoft.Office.Interop.Excel.Application();

                oBook = oExcel.Workbooks.
                    Open(myDir.FullName + "\\" + fname + "", 0, false, 5, "", "", true,
                    Microsoft.Office.Interop.Excel.XlPlatform.xlWindows, "\t", false, false, 0, true, 1, 0);
                Microsoft.Office.Interop.Excel.Sheets WRss = oBook.Sheets;

                //oModule = oBook.VBProject.VBComponents.Add(VBIDE.vbext_ComponentType.vbext_ct_StdModule);

                //sCode = "sub Macro()\r\n" +

                //    System.IO.File.ReadAllText(templatemyDir.FullName + "\\PerformanceDeck_macro.txt") +
                //        "\nend sub";
                //oModule.CodeModule.AddFromString(sCode);

                //oExcel.GetType().InvokeMember("Run",
                //                System.Reflection.BindingFlags.Default |
                //                System.Reflection.BindingFlags.InvokeMethod,
                //                null, oExcel, new string[] { "Macro" });



                /////////////////////////////////////
                oBook.RefreshAll();
                oBook.Save();
                oBook.Close(false, myDir.FullName + "\\" + fname + "", null);


                System.Runtime.InteropServices.Marshal.FinalReleaseComObject(oBook);
                oBook = null;

                oExcel.Quit();
                oExcel = null;



                GC.Collect();
                GC.WaitForPendingFinalizers();
                GC.Collect();
                GC.WaitForPendingFinalizers();



            }

        }

        public void ReleaseObject(object o)
        {
            try
            {
                if (o != null)
                    System.Runtime.InteropServices.Marshal.ReleaseComObject(o);
            }
            catch (Exception) { }
            finally { o = null; }
        }
        private string GetUserID()
        {
            string[] machineUsers = User.Identity.Name.Split('\\');
            if (machineUsers.Length == 2)
                return machineUsers[1];
            return "";
        }

        public DataSet Get_Data(string UserId, string SL, string Finyear, string duration, string Period, string Type)
        {

            DataSet ds = new DataSet();
            SqlCommand cmd = new SqlCommand("sp_Project-wise_Contract-wise_Summary", con);
            cmd.CommandTimeout = int.MaxValue;
            cmd.Parameters.AddWithValue("@UserId", UserId);
            cmd.Parameters.AddWithValue("@SU", SL);
            cmd.Parameters.AddWithValue("@fyr", Finyear);
            cmd.Parameters.AddWithValue("@duration", duration);
            cmd.Parameters.AddWithValue("@Period", Period);
            cmd.Parameters.AddWithValue("@Type", Type);
            cmd.CommandType = CommandType.StoredProcedure;
            SqlDataAdapter sdr = new SqlDataAdapter(cmd);
            sdr.Fill(ds);
            return ds;
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TopAccount/Views/Top/Index.cshtml
@model TopAccount.Models.Consolidated

@{
    ViewBag.Title = "Index";
}

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Select2/JScriptSelect2.js"></script>
<link href="~/Select2/select2.css" rel="stylesheet" />

<script>
    var _tmr;
    $(function () {
        initdropdown();

        $("#btnGenerate").click(function () {

            $('#cookieValue').val(Date.now().toString());

            $("#searchimg").css("display", "block");


            _tmr = window.setInterval(function () {
                var _str = 'dlc=' + $('#cookieValue').val();
                if (document.cookie.indexOf(_str) !== -1) {
                    // hide animation
                    $("#searchimg").css("display", "none");
                }
            }, 100);

        })

        var val = '@ViewBag.Message';
        if (val != '') {
            alert(val)
        }


    })

    function initdropdown() {
        $("#ddlServiceLine,#ddlFinYear,#ddlFrom,#ddlTo").select2({
            selectOnClose: true,
            minimumResultsForSearch: -1
        })




        //$("#ddlDuration").select2({
        //    selectOnClose: true,
        //    minimumResultsForSearch: -1

        //})
        //.on("change", function (e) {
        //        var Duration = $(this).children("option:selected").val();
        //        $('#ddlPeriod').empty();

        //        if (Duration == "QTD" || Duration == "HTD") {
        //            $('#ddlPeriod').prop('disabled', false);

        //            if (Duration == "QTD") {
        //                $('#ddlPeriod').append('<option  value="Q1">Q1</option>');
        //                $('#ddlPeriod').append('<option value="Q2">Q2</option>');
        //                $('#ddlPeriod').append('<option value="Q3">Q3</option>');
        //                $('#ddlPeriod').append('<option value="Q4">Q4</option>');
        //                $('#ddlPeriod').val("Q1").trigger('change');
        //            }
        //            else if (Duration == "HTD") {
        //                $('#ddlPeriod').append('<option value="H1">H1</option>');
        //                $('#ddlPeriod').append('<option value="H2">H2</option>');
        //                $('#ddlPeriod').val("H1").trigger('change');
        //            }
        //        }
        //        else {
        //            $('#ddlPeriod').append('<option  value="NA">NA</option>');
        //            $('#ddlPeriod').val("NA").trigger('change');
        //            $('#ddlPeriod').prop('disabled', true);
        //        }
        //    });

        //$('#ddlFrom').val("202004").trigger('change');
        //$('#ddlTo').val("202004").trigger('change');
    }

</script>

<style>
    .select2-container--default .select2-results > .select2-results__options {
        max-height: 100px !important;
    }

    body {
        padding-top: 10px !important;
        padding-bottom: 20px;
    }
</style>

<div style="height:250px;width:900px;margin:0px auto;padding-top:100px">
    @using (Html.BeginForm("Index", "Top"))
    {

        <div style="width:480px;margin:0px auto;">


            <div style="float:left;margin-top:3px;margin-right:10px"><span style="font-family:Calibri">ServiceLine:</span></div>
            <div style="float:left;margin-right:10px">
                @Html.DropDownListFor(m => m.item2.SLId, Model.item2.SL, new { @name = "SL", @Id = "ddlServiceLine", style = "width: 100px;" })
            </div>

            
                <div style="float:left;"><button name="submit" type="submit" id="btnGenerate" value="Generate" class="btn btn-success">Generate</button></div>
                @Html.Hidden("cookieValue")
                <div id="kk" style="float:left;margin-left:20px;"><img id="searchimg" src="@Url.Content("~/Images/load.gif")" alt="Image" width="30" height="30" style="display:none" /></div>
            



        </div>

    }
</div>